import fs from 'node:fs';
import path from 'node:path';
import {prepareImages,optimizeHtml} from './images.mjs';
import {marked} from 'marked';
const root=process.cwd(),out=path.join(root,'_site');
fs.rmSync(out,{recursive:true,force:true});
fs.mkdirSync(out,{recursive:true});
fs.cpSync('img',path.join(out,'img'),{recursive:true});
fs.copyFileSync('assets/style.css',path.join(out,'style.css'));
fs.mkdirSync(path.join(out,'js'),{recursive:true});
fs.copyFileSync('js/legacy-links.js',path.join(out,'js/legacy-links.js'));
fs.copyFileSync('assets/site.js',path.join(out,'js/site.js'));
fs.writeFileSync(path.join(out,'.nojekyll'),'');
const imageMap=await prepareImages(out);
const routes=[];
const read=(l,n)=>JSON.parse(fs.readFileSync(`data/${l}/${n}.json`,'utf8'));
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const md=x=>marked.parse(Array.isArray(x)?x.join('\n\n'):String(x??''));
const plain=x=>String(x??'').replace(/<[^>]*>/g,' ').replace(/\*\*/g,'');
const url=(l,p='')=>(l==='ko'?'/ko/':'/')+(p?p+'/':'');
const asset=p=>'/'+String(p).replace(/^\//,'');
function photo(p,alt,cls=''){return p&&fs.existsSync(path.join(out,p))?`<img class="${cls}" src="${esc(asset(p))}" alt="${esc(alt)}" loading="lazy">`:'';}
const words={en:{join:'Join Us',faculty:'Hongjo Kim',news:'News',about:'About the lab',home:'Home',members:'People',publications:'Publications',projects:'Projects',teaching:'Teaching',blog:'Blog',album:'Album',more:'Read more',profile:'Research & background',news:'Latest news',intro:'About the lab'},ko:{join:'대학원 지원',faculty:'김홍조 교수',news:'연구실 소식',about:'연구실 소개',home:'홈',members:'구성원',publications:'연구실적',projects:'연구과제',teaching:'강의',blog:'블로그',album:'앨범',more:'글 읽기',profile:'연구 및 상세 소개',news:'연구실 소식',intro:'연구실 소개'}};
const base=fs.readFileSync('templates/home.html','utf8');
const originalHead=base.match(/<head>[\s\S]*?<\/head>/)[0];
function header(l,p){const active=p.split('/')[0];return `<a class="skip" href="#main">${l==='ko'?'본문 바로가기':'Skip to content'}</a><header><a class="brand" href="${url(l)}"><span class="mark" aria-hidden="true">SI<span>⌁</span></span><span>Smart Infrastructure Lab<small>YONSEI UNIVERSITY</small></span></a><button class="menu-toggle" type="button" aria-controls="site-nav" aria-expanded="false" hidden>${l==='ko'?'메뉴':'Menu'}</button><nav id="site-nav" aria-label="${l==='ko'?'주 메뉴':'Main navigation'}">${['members','publications','projects','teaching','blog','album','join'].map(k=>`<a href="${url(l,k)}" ${active===k?'aria-current="page"':''}>${words[l][k]}</a>`).join('')}<a class="language" lang="${l==='ko'?'en':'ko'}" href="${url(l==='ko'?'en':'ko',p)}">${l==='ko'?'EN':'한국어'}</a></nav></header>`;}
function footer(l){let d=read(l,'footer');return `<footer><div><a class="footer-brand" href="${url(l)}">Smart Infrastructure Lab</a><p>${d.address}<br>${d.contact}</p><a href="${url(l,'about')}">${words[l].about}</a> · <a href="${url(l,'join')}">${words[l].join}</a></div><a href="#">${l==='ko'?'맨 위로 ↑':'Back to top ↑'}</a></footer>`;}
function save(l,p,title,body,description=''){
 const canonical='https://hongjo.github.io'+url(l,p),desc=description||title+' — Smart Infrastructure Lab, Yonsei University';
 let h=originalHead.replace(/<title>.*?<\/title>/,`<title>${esc(title==='Smart Infrastructure Lab'?'Smart Infrastructure Lab | Yonsei University':title+' | Smart Infrastructure Lab')}</title>`).replace(/<meta name="description" content="[^"]*">/,`<meta name="description" content="${esc(desc)}">`).replace('href="style.css"','href="/style.css"');
 h=h.replace('</head>',`<link rel="canonical" href="${canonical}"><link rel="alternate" hreflang="en" href="https://hongjo.github.io${url('en',p)}"><link rel="alternate" hreflang="ko" href="https://hongjo.github.io${url('ko',p)}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(desc)}"><meta property="og:url" content="${canonical}"></head>`);
 let html=`<!DOCTYPE html><html lang="${l}">${h}<body>${header(l,p)}<main id="main">${body}</main>${footer(l)}</body></html>`;
 html=html.replace(/(src|href)="img\//g,'$1="/img/').replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,'').replace(/\son\w+="[^"]*"/g,'').replace(/href="javascript:[^"]*"/gi,'href="#"');
 html=optimizeHtml(html,imageMap).replace('</body>',`<script src="/js/site.js" defer></script>${p?'':'<script src="/js/legacy-links.js" defer></script>'}</body>`);
 let dest=path.join(out,url(l,p),'index.html');fs.mkdirSync(path.dirname(dest),{recursive:true});fs.writeFileSync(dest,html);routes.push({l,p});
}
function heading(l,p,subtitle=''){return `<div class="page-heading"><p class="eyebrow">SMART INFRASTRUCTURE LAB / ${p.toUpperCase()}</p><h1>${words[l][p]}</h1>${subtitle?`<p>${subtitle}</p>`:''}</div>`;}
function blogCards(l,limit=Infinity){return `<div class="blog-grid">${read(l,'blog').posts.slice(0,limit).map(p=>`<article class="blog-card"><a href="${url(l,'blog/'+p.slug)}">${photo(p.cover,plain(p.title))}<div class="blog-card-body"><time datetime="${p.date}">${p.date}</time><h3>${esc(p.title)}</h3><p>${esc(plain(p.subtitle))}</p><span class="read-link">${words[l].more} ↗</span></div></a></article>`).join('')}</div>`;}
const koMembers=read('ko','members'),enMembers=read('en','members');
const studies=JSON.parse(fs.readFileSync('data/research.json','utf8'));
const publications=read('ko','publications');
function paperFor(r){return publications.journal_papers.find(p=>p.title.toLowerCase().includes(r.match.toLowerCase()));}
function resources(l,r){const p=paperFor(r);return `<div class="resource-links">${p?.doi?`<a href="https://doi.org/${esc(p.doi)}" target="_blank" rel="noopener noreferrer">${l==='ko'?'논문':'Paper'} ↗</a>`:''}${r.code?`<a href="${esc(r.code)}" target="_blank" rel="noopener noreferrer">Code ↗</a>`:''}<a href="${url(l,'blog/'+r.slug)}">${l==='ko'?'연구 해설':'Research story'} →</a></div>`;}
function featured(l){return `<section class="section selected-research" id="selected-research"><div class="section-head"><p class="eyebrow">SELECTED RESEARCH</p><h2>${l==='ko'?'문제에서 시작해,<br>연구로 답합니다.':'From engineering problems<br>to research contributions.'}</h2><a class="text-link" href="${url(l,'publications')}">${l==='ko'?'전체 연구실적':'All publications'} ↗</a></div><div class="featured-grid">${studies.map(r=>`<article>${photo(r.image,r[l].title)}<div><p class="eyebrow">${esc(paperFor(r)?.journal||'RESEARCH')}</p><h3>${esc(r[l].title)}</h3><p>${esc(r[l].problem)}</p><p>${esc(r[l].idea)}</p>${resources(l,r)}</div></article>`).join('')}</div></section>`;}
function topicTags(p){const t=p.title.toLowerCase();return [...new Set([/vision|image|crack|detection|segmentation|visual/.test(t)?'vision':'',/3d|reconstruction|photogram|sonar|underwater/.test(t)?'sensing':'',/physics|diffusion|levee|embankment|pore/.test(t)?'physics':'',/language|retrieval|agent|document|rag|knowledge/.test(t)?'agents':'',/economic|cost|financial|safety|risk/.test(t)?'safety':''].filter(Boolean))].join(',');}
function newsItems(l,items){return `<div class="news-list">${items.map(n=>`<article><time>${esc(n.date)}</time><div><h3>${esc(n.title)}</h3>${md(n.description)}${n.link?`<a class="text-link" href="${url(l,n.link)}">${l==='ko'?'자세히 보기':'Read more'} →</a>`:''}</div></article>`).join('')}</div>`;}
function profileMarkdown(x){return md(x).replace(/<h1>/g,'<h2>').replace(/<\/h1>/g,'</h2>');}
const vision=JSON.parse(fs.readFileSync('data/vision.json','utf8'));
function visionSection(l){return `<section class="section vision-section" id="our-vision" aria-labelledby="vision-heading"><p class="eyebrow" lang="en">${esc(vision.title)}</p><h2 id="vision-heading" lang="en">Dream Big.<br>Aim for the Best.<br><em>Build a Better World.</em></h2><p class="vision-statement" lang="en">${esc(vision.en)}</p><blockquote lang="ko">${esc(vision.ko)}</blockquote></section>`;}
function peopleSection(l){return `<section class="section people-values" id="people-we-seek" aria-labelledby="people-heading"><p class="eyebrow" lang="en">${esc(vision.peopleTitle)}</p><h2 id="people-heading" lang="en">${esc(vision.peopleMotto)}</h2><div class="values-grid">${vision.values.map((v,i)=>`<article><span class="value-number" aria-hidden="true">0${i+1}</span><h3 lang="en">${esc(v.title)}</h3><p>${esc(v[l])}</p></article>`).join('')}</div></section>`;}
const counts={};
for(const l of ['en','ko']){
 const w=words[l],home=read(l,'main');
 let hero=base.match(/<section class="hero">[\s\S]*?<\/section>/)[0];
 if(l==='ko')hero=hero.replace('Intelligence for<br>the infrastructure<br><em>we depend on.</em>','사회를 지탱하는<br>인프라에<br><em>지능을 더합니다.</em>').replace('Connecting artificial intelligence with engineering knowledge to understand, inspect, and protect the built environment.','인공지능과 공학 지식을 연결하여 사회기반시설을 이해하고, 점검하고, 안전하게 관리하는 방법을 연구합니다.').replace('Explore our research','연구분야 살펴보기');
 let research=base.match(/<section class="section" id="research">[\s\S]*?<\/section>/)[0];
 if(l==='ko'){
  const translations={'Built on engineering.<br>Advanced through AI.':'공학을 기반으로,<br>AI로 확장합니다.','Methods that connect visual observations, physical processes, and engineering knowledge.':'영상 관측, 물리적 과정, 공학 지식을 연결하는 방법론을 연구합니다.','Visual intelligence<br>for infrastructure':'인프라를 위한<br>시각 지능','Computer vision for damage assessment, crack segmentation and matting, and automated inspection of civil infrastructure.':'컴퓨터 비전을 활용하여 사회기반시설의 손상을 평가하고, 균열을 정밀하게 인식하며, 점검을 자동화합니다.','3D sensing &<br>reconstruction':'3차원 센싱과<br>재구성','Photogrammetry, image enhancement, and 3D modeling across terrestrial and underwater environments.':'수중과 육상 환경을 대상으로 사진측량, 영상 선명화, 3차원 모델링 기술을 연구합니다.','Physics-informed<br>intelligence':'물리 기반<br>인공지능','Integrating physical principles with machine learning to reconstruct pore water pressure fields and support embankment failure detection.':'물리 법칙과 기계학습을 결합하여 간극수압장을 복원하고 제방 붕괴 조기 감지를 지원합니다.','AI for engineering<br>decisions':'공학 의사결정을<br>위한 AI','Multimodal models, retrieval-augmented generation, and AI agents for construction safety, engineering documents, and design calculations.':'멀티모달 모델, 검색 증강 생성, AI 에이전트를 활용하여 건설 안전, 공학 문서 분석, 설계 계산을 지원합니다.'};
  for(const [a,b] of Object.entries(translations)) research=research.replace(a,b);
 }
 hero=hero.replace('Connecting artificial intelligence with engineering knowledge to understand, inspect, and protect the built environment.','Computer vision, physics-informed AI, and engineering agents for construction safety and infrastructure inspection.').replace('인공지능과 공학 지식을 연결하여 사회기반시설을 이해하고, 점검하고, 안전하게 관리하는 방법을 연구합니다.','컴퓨터 비전, 물리 기반 AI, 공학 에이전트로 건설 안전과 인프라 점검의 문제를 해결합니다.').replaceAll('href="#research"','href="#selected-research"').replace('Explore our research','Explore our research');
 hero=hero.replace('</a></div><div class="research-map"',`</a><a class="hero-join" href="${url(l,'join')}">${words[l].join} ↗</a></div><div class="research-map"`);
 let homeBody=hero+visionSection(l)+featured(l)+research;
 homeBody+=`<section class="section news-section"><div class="section-head"><p class="eyebrow">FROM THE LAB</p><h2>${w.news}</h2><a class="text-link" href="${url(l,'news')}">${l==='ko'?'전체 소식':'All news'} ↗</a></div>${newsItems(l,home.news.items.slice(0,4))}</section>`;
 homeBody+=`<section class="section"><div class="section-head"><p class="eyebrow">RESEARCH STORIES</p><h2>${w.blog}</h2><a class="text-link" href="${url(l,'blog')}">${l==='ko'?'모든 글 보기':'View all stories'} ↗</a></div>${blogCards(l,3)}</section>`;
 homeBody+=`<section class="lab-photo-band">${photo('img/album/251101/25가을1.jpg',l==='ko'?'2025 연구실 단풍 워크샵':'Lab autumn workshop, 2025')}<span><a href="${url(l,'members')}">${l==='ko'?'함께 연구하고, 함께 성장합니다.':'A shared curiosity. A collective effort.'} ↗</a></span></section>`;
 save(l,'news',w.news,heading(l,'news')+`<section class="section">${newsItems(l,home.news.items)}</section>`);
 save(l,'about',w.about,heading(l,'about')+`<section class="section original-intro"><div class="prose">${home.labIntro.paragraphs.map(md).join('')}</div></section>`);
 homeBody+=peopleSection(l);
 let contact=base.match(/<section class="contact section"[\s\S]*?<\/section>/)[0];if(l==='ko')contact=contact.replace('Let’s connect<br>ideas to infrastructure.','아이디어를 연결하여<br>인프라의 미래를 만듭니다.').replace('For research collaboration and graduate research inquiries, contact Professor Hongjo Kim.','공동연구 및 대학원 진학에 관한 문의는 김홍조 교수에게 연락해 주시기 바랍니다.').replace('Department of Civil & Environmental Engineering<br>Yonsei University<br>Seoul, South Korea','연세대학교 건설환경공학과<br>서울특별시 서대문구 연세로 50<br>제1공학관 N504호');contact=contact.replace('<a class="email"',`<p><a class="text-link" href="${url(l,'join')}">${w.join} ↗</a></p><a class="email"`);homeBody+=contact;
 save(l,'','Smart Infrastructure Lab',homeBody);
 // Korean roster is the newer source; use it for category membership in both languages.
 let memberBody=heading(l,'members',l==='ko'?'서로 다른 전문성을 연결하는 연구 공동체':'A research community connecting different perspectives.');
 const prof=read(l,'members').professor;
 const faculty=`<section class="section faculty"><div>${photo(prof.photo,prof.name,'faculty-photo')}<p class="eyebrow">LAB DIRECTOR</p><h2>${esc(prof.name)}</h2><a class="text-link" href="mailto:${esc(prof.email)}">${esc(prof.email)} ↗</a></div><div class="prose">${profileMarkdown(prof.description)}</div></section>`;
 save(l,'faculty',w.faculty,heading(l,'faculty')+faculty);
 memberBody+=`<section class="section faculty-summary">${photo(prof.photo,prof.name,'faculty-photo')}<div><p class="eyebrow">LAB DIRECTOR</p><h2>${esc(prof.name)}</h2><p>${l==='ko'?'연세대학교 건설환경공학과 부교수':'Associate Professor, Civil and Environmental Engineering, Yonsei University'}</p><p>${l==='ko'?'컴퓨터 비전 · 물리 기반 AI · 인프라 점검 · 공학 에이전트':'Computer vision · Physics-informed AI · Infrastructure inspection · Engineering agents'}</p><a class="text-link" href="${url(l,'faculty')}">${l==='ko'?'경력 및 연구활동 전체 보기':'View full faculty profile'} ↗</a></div></section>`;
 read(l,'members').categories.forEach((c,i)=>{
 memberBody+=`<section class="section member-section"><div class="category-title"><h2>${esc(c.title)}</h2><span>${String(c.members.length).padStart(2,'0')}</span></div><div class="member-grid">`;
 for(const m of c.members){memberBody+=`<article class="member-card">${photo(m.photo,m.name,'member-photo')||`<div class="member-initial" aria-hidden="true">${esc(m.name.slice(0,2))}</div>`}<h3>${esc(m.name)}</h3><p class="member-role">${esc(m.role)}</p><div class="member-interests">${md(m.interests)}</div>${m.details?.length?`<details><summary>${w.profile}</summary><div class="prose">${profileMarkdown(m.details)}</div></details>`:''}</article>`;}
 memberBody+='</div></section>';
 });save(l,'members',w.members,memberBody);
 let pub=read('ko','publications'),pubBody=heading(l,'publications',l==='ko'?'저널 · 국제 및 국내 학술대회 · 특허':'Journals, conference proceedings, and patents.');
 const labels=l==='ko'?['저널 논문','국제 학술대회','국내 학술대회','특허']:['Journal articles','International conferences','Domestic conferences','Patents'];
 pubBody+=`<nav class="subnav" aria-label="${l==='ko'?'연구실적 분류':'Publication categories'}">${Object.keys(pub).map((k,i)=>`<a href="#${k}">${labels[i]} <span>${pub[k].length}</span></a>`).join('')}</nav>`;
 const years=[...new Set(Object.values(pub).flat().map(p=>p.year))].sort((a,b)=>b-a);
 const topics=l==='ko'?{vision:'영상 인식·균열',sensing:'3D·센싱',physics:'물리 기반 AI',agents:'언어모델·에이전트',safety:'안전·경제성'}:{vision:'Vision & cracks',sensing:'3D & sensing',physics:'Physics-informed AI',agents:'Language models & agents',safety:'Safety & economics'};
 pubBody+=`<section class="publication-controls" data-publication-filters hidden><label>${l==='ko'?'제목·저자·키워드 검색':'Search titles, authors, and keywords'}<input type="search" aria-label="${l==='ko'?'연구실적 검색':'Search publications'}" placeholder="${l==='ko'?'예: crack, RAG, Kim':'e.g. crack, RAG, Kim'}"></label><label>${l==='ko'?'연도':'Year'}<select name="year"><option value="">${l==='ko'?'전체 연도':'All years'}</option>${years.map(y=>`<option>${y}</option>`).join('')}</select></label><label>${l==='ko'?'연구주제':'Topic'}<select name="topic"><option value="">${l==='ko'?'전체 주제':'All topics'}</option>${Object.entries(topics).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select></label><button type="button">${l==='ko'?'초기화':'Reset'}</button><p data-result-count role="status" aria-live="polite"></p></section><p class="empty-results" data-empty hidden>${l==='ko'?'일치하는 연구실적이 없습니다. 검색어 또는 필터를 변경해 주세요.':'No matching publications. Try a different search or filter.'}</p>`;
 Object.entries(pub).forEach(([k,items],i)=>{pubBody+=`<section class="section publication-section" id="${k}"><div class="category-title"><h2>${labels[i]}</h2><span>${items.length}</span></div><div class="publication-list">${items.map(p=>{const link=p.url||(p.doi?'https://doi.org/'+p.doi:'');return `<article data-publication data-year="${p.year}" data-topics="${topicTags(p)}"><div class="pub-year">${p.year}</div><div><h3>${link?`<a href="${esc(link)}" target="_blank" rel="noopener noreferrer">${esc(p.title)} ↗</a>`:esc(p.title)}</h3><p class="authors">${esc((p.authors||p.inventors||[]).join(', '))}</p><p class="venue">${esc([p.journal||p.conference||p.patent_type,p.volume,p.pages,p.location,p.date_range,p.publisher,p.patent_number,p.country,p.status].filter(Boolean).join(' · '))}</p>${studies.filter(r=>paperFor(r)?.title===p.title).map(r=>resources(l,r)).join('')}</div></article>`;}).join('')}</div></section>`;});save(l,'publications',w.publications,pubBody);
 let projects=read(l,'projects').projects;

 let projectsBody=heading(l,'projects',l==='ko'?'현장의 질문을 연구로 연결합니다.':'Connecting engineering questions with applied research.');projectsBody+=`<section class="section all-projects"><div class="project-list">${projects.map(p=>`<article><div><span class="project-org">${esc(p.funding)}</span><p class="years">${esc(p.period)}</p></div><div><h3>${esc(p.title)}</h3>${md(p.description)}${p.image?photo(p.image,p.title):''}${p.results?.length?md(p.results):''}</div></article>`).join('')}</div></section>`;save(l,'projects',w.projects,projectsBody);
 let t=read(l,'teaching');let teachBody=heading(l,'teaching',l==='ko'?'공학적 사고와 계산 역량을 함께 기릅니다.':'Developing engineering judgment and computational skills.');
 for(const s of t.semesters){teachBody+=`<section class="section semester"><h2>${esc(s.title)}</h2><div class="course-grid">${s.courses.map(c=>`<article><p class="eyebrow">${esc(c.level||c.code)}</p><h3>${esc(c.title)}</h3>${c.time||c.location?`<dl>${c.time?`<dt>${t.labels.classTime}</dt><dd>${md(c.time)}</dd>`:''}${c.location?`<dt>${t.labels.location}</dt><dd>${md(c.location)}</dd>`:''}</dl>`:''}${md(c.description)}${c.materials?.map(m=>`<a class="text-link" href="${esc(m.link)}">${esc(m.title)} ↗</a>`).join('')||''}</article>`).join('')}</div></section>`;}save(l,'teaching',w.teaching,teachBody);
 save(l,'blog',w.blog,heading(l,'blog',l==='ko'?'논문 속 아이디어와 연구실의 이야기':'The ideas behind our papers. Stories from the lab.')+`<section class="section">${blogCards(l)}</section>`);
 const posts=read(l,'blog').posts;
 posts.forEach((p,i)=>{const source=fs.readFileSync(p.md,'utf8');const study=studies.find(r=>r.slug===p.slug);let toc=[];let content=md(source).replace(/<h([23])>([\s\S]*?)<\/h\1>/g,(_,level,text)=>{const id='section-'+(toc.length+1);toc.push({id,text:plain(text),level});return `<h${level} id="${id}">${text}</h${level}>`;});const summary=study?`<section class="post-summary"><h2>${l==='ko'?'연구 한눈에 보기':'Research at a glance'}</h2><dl>${[['problem',l==='ko'?'문제':'Problem'],['idea',l==='ko'?'핵심 아이디어':'Key idea'],['use',l==='ko'?'활용':'Application']].map(([key,label])=>`<dt>${label}</dt><dd>${esc(study[l][key])}</dd>`).join('')}</dl>${resources(l,study)}</section>`:'';const contents=toc.length?`<nav class="post-toc" aria-label="${l==='ko'?'목차':'Table of contents'}"><h2>${l==='ko'?'목차':'On this page'}</h2><ol>${toc.map(t=>`<li><a href="#${t.id}">${esc(t.text)}</a></li>`).join('')}</ol></nav>`:'';const body=`<div class="post-header"><a class="text-link" href="${url(l,'blog')}">← ${w.blog}</a><time>${p.date}</time><h1>${esc(p.title)}</h1><div class="post-subtitle">${md(p.subtitle)}</div></div><article class="prose post-body">${summary}${contents}${content}</article><div class="post-navigation"><a class="text-link" href="${url(l,'blog')}">← ${l==='ko'?'글 목록':'All stories'}</a>${i+1<posts.length?`<a href="${url(l,'blog/'+posts[i+1].slug)}">${l==='ko'?'다음 글':'Next story'} →<span>${esc(posts[i+1].title)}</span></a>`:''}</div>`;save(l,'blog/'+p.slug,p.title,body,plain(p.subtitle||p.title));});
 const a=read(l,'admissions');save(l,'join',a.title,heading(l,'join',a.subtitle)+peopleSection(l)+`<section class="section admissions"><div class="application-panel"><p class="eyebrow">GRADUATE APPLICATIONS</p><h2>${esc(a.apply)}</h2><p>${esc(a.intro)}</p><ol>${a.docs.map(d=>`<li>${esc(d)}</li>`).join('')}</ol><a class="button" href="mailto:hongjo@yonsei.ac.kr">${esc(a.email)} ↗</a><p class="application-email">hongjo@yonsei.ac.kr</p></div><div class="international-panel"><h2>${esc(a.international)}</h2><article><h3>${esc(a.masters)}</h3><p>${esc(a.masters_text)}</p></article><article><h3>${esc(a.phd)}</h3><p>${esc(a.phd_text)}</p><div class="funding-note"><h4>${esc(a.program)}</h4><p>${esc(a.program_text)}</p></div></article><article><h3>${esc(a.letter)}</h3><p>${esc(a.letter_text)}</p></article><p class="policy-date">${esc(a.date)}</p></div></section>`);
 let albums=read(l,'album').albums;let albumBody=heading(l,'album',l==='ko'?'연구실에서 함께한 순간들':'Moments beyond the research.');
 albums.forEach(a=>{albumBody+=`<section class="section album-section"><div class="category-title"><h2>${esc(a.title)}</h2><span>${esc(a.description)}</span></div><div class="album-grid">${a.images.map(im=>`<figure><a href="${esc(asset(im.fullSize||im.src))}" target="_blank" rel="noopener noreferrer">${photo(im.src,im.caption)}</a><figcaption>${esc(im.caption)}</figcaption></figure>`).join('')}</div></section>`;});save(l,'album',w.album,albumBody);
 counts[l]={members:koMembers.categories.reduce((s,c)=>s+c.members.length,0),projects:projects.length,blog:posts.length,albums:albums.length,photos:albums.reduce((s,a)=>s+a.images.length,0),semesters:t.semesters.length};
}
fs.writeFileSync(path.join(out,'sitemap.xml'),'<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+routes.map(r=>`<url><loc>https://hongjo.github.io${url(r.l,r.p)}</loc></url>`).join('')+'</urlset>');
fs.writeFileSync(path.join(out,'robots.txt'),'User-agent: *\nAllow: /\nSitemap: https://hongjo.github.io/sitemap.xml\n');
fs.writeFileSync(path.join(out,'build-info.json'),JSON.stringify({source:process.env.GITHUB_SHA||'local',routes:routes.length,counts}));
console.log(counts);
